# Check out https://hub.docker.com/_/node to select a new base image
FROM 950066988925.dkr.ecr.ap-southeast-1.amazonaws.com/node:12-alpine

RUN mkdir -p /home/app

WORKDIR /home/app

COPY package*.json ./

# Bundle app source code
COPY . .

RUN yarn install

RUN yarn build

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0

CMD [ "npm", "run", "start:production" ]
